# Generated by Django 5.2 on 2025-05-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author_name', models.CharField(max_length=100)),
                ('author_bio', models.CharField(blank=True, max_length=255)),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('category', models.CharField(max_length=100)),
                ('content', models.TextField(help_text='Use <h2> for subheadings to build Table of Contents')),
                ('excerpt', models.TextField()),
                ('published_date', models.DateField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog_thumbnails/')),
                ('tags', models.ManyToManyField(to='main.blogtag')),
            ],
        ),
    ]
